# Generated by Django 3.1.4 on 2022-04-04 02:36

from django.db import migrations

from users import models


def populate(apps, shema_editor):
    users = [{
        'first_name': 'Dam',
        'last_name': 'Dom',
        'username': 'Damien',
        'email': 'damien@gmail.com',
        'role': 'MANAGER',
        'is_superuser': True
    },{
        'first_name': 'Pim',
        'last_name': 'Pam',
        'username': 'Jamy',
        'email': 'jamy@gmail.com',
        'role': 'SELLER',
        'is_superuser': False
    },{
        'first_name': 'Vip',
        'last_name': 'Vap',
        'username': 'François',
        'email': 'francois@gmail.com',
        'role': 'SUPPORT', 
        'is_superuser': False
    },{
        'first_name': 'Rim',
        'last_name': 'Rum',
        'username': 'Marie',
        'email': 'marie@gmail.com',
        'role': 'MANAGER', 
        'is_superuser': True
    },{
        'first_name': 'Jim',
        'last_name': 'Jam',
        'username': 'Patrick',
        'email': 'patrick@gmail.com',
        'role': 'SELLER', 
        'is_superuser': False
    },{
        'first_name': 'Toum',
        'last_name': 'Tim',
        'username': 'Xavier',
        'email': 'xavier@gmail.com',
        'role': 'SUPPORT', 
        'is_superuser': False
    }]

    for user in users:
        models.User(
            first_name=user['first_name'],
            last_name=user['last_name'],
            username=user['username'],
            email=user['email'],
            password='pbkdf2_sha256$216000$RzXbAJyBUB1g$egZc3l/H1P6aQ80aTDA37f5Yb+wTfx+WBZDqujfBxHY=',
            role=user['role'],
            is_superuser=user['is_superuser']
        ).save()


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20220404_0236'),
    ]

    operations = [
        migrations.RunPython(populate)
    ]
