# Generated by Django 4.0.1 on 2022-02-11 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_phone_user_role_alter_user_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$320000$L6khXQtNTMetZuru1H3OP6$RiqoWu9cahq4nn5I7N8IackYEG0vH4GUxY5IDVWQ818=', max_length=255),
        ),
    ]
