# Generated by Django 3.1.4 on 2022-04-04 03:03

from django.db import migrations

from crm import models
from users.models import User


def populate(apps, shema_editor):
    customers = [
        {
            'last_name': 'Hurley',
            'email': 'hurley@gmail.com',
            'existing': True,
            'seller': User.objects.get(id=5)
        },{
            'last_name': 'Kate',
            'email': 'kate@gmail.com',
            'existing': False,
            'seller': User.objects.get(id=2)
        },{
            'last_name': 'Jack',
            'email': 'jack@gmail.com',
            'existing': False,
            'seller': User.objects.get(id=5)
        },{
            'last_name': 'John',
            'email': 'john@gmail.com',
            'existing': True,
            'seller': User.objects.get(id=2)
        }
    ]

    for customer in customers:
        models.Customer(
            last_name=customer['last_name'],
            email=customer['email'],
            existing=customer['existing'],
            seller=customer['seller'],
        ).save()

    events = [
        {
            'name': 'Grosse teuf',
            'location': 'Lyon',
            'date_event': '04/04/2022 23:00'
        },{
            'name': 'New year',
            'location': 'Bangkok',
            'date_event': '31/12/2022 11:00'
        },{
            'name': 'Couronnement de Charlemagne',
            'location': 'Rome',
            'date_event': '25/12/2022 12:00'
        }
    ]

    contracts = [
        {
            'support': 3,
            'seller': 5,
            'customer': 3,
            'due': 300,
        },{
            'support': 6,
            'seller': 5,
            'customer': 1,
            'due': 500,
        },{
            'support': 3,
            'seller': 5,
            'customer': 1,
            'due': 2000,
        },{
            'support': 6,
            'seller': 2,
            'customer': 2,
            'due': 20,
        },{
            'support': 3,
            'seller': 2,
            'customer': 4,
            'due': 4000000,
        }
    ]

    for contract in contracts:
        new_contract = models.Contract(
            support=User.objects.get(id=contract['support']),
            seller=User.objects.get(id=contract['seller']),
            customer=models.Customer.objects.get(id=contract['customer']),
            due=contract['due'],
        ).save()
    
    i=1
    for event in events:
        contract = models.Contract.objects.get(id=i)
        contract.sign(
            name_event=event['name'],
            location_event=event['location'],
            date_event=event['date_event'],
        )
        i+=1


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0002_auto_20220404_0236'),
    ]

    operations = [
        migrations.RunPython(populate)
    ]
